### ISSUE TITLE
создание страницы регистрации

### ISSUE THREAD

**Issue by onethps** [andreu6454/friday-project#2]
отправить запрос, показать ошибку или перейти на страницу логинизации

**Comment by andreu6454** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/70666153/207843353-f12651c9-2922-486f-b1ec-1f969707e911.png">

**Comment by andreu6454** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/70666153/207843482-fccb2aaa-1dfa-483c-b386-3a8a4569cc82.png">
добавил ui и редирект на логин
