### ISSUE TITLE
(Страница с карточками) При клике на нее возвращаться на страницу с колодами

### ISSUE THREAD

**Issue by onethps** [andreu6454/friday-project#33]
Нужно создать компонент для переиспользования кнопки, так как кнопка уже есть в двух местах

![image](https://user-images.githubusercontent.com/40173213/209039727-55536dc9-8ac1-4f67-8d04-b23af158eb09.png)

**Comment by andreu6454** [comment]
<img width="925" alt="image" src="https://user-images.githubusercontent.com/70666153/209979829-7b824e84-14da-4297-a0aa-e65067f53488.png">
